"""Settings in User

Revision ID: 91b42eb5c677
Revises: d04cc67b482b
Create Date: 2025-07-19 11:57:39.717617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b42eb5c677'
down_revision: Union[str, None] = 'd04cc67b482b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hobby', sa.String(), nullable=True))
    op.add_column('users', sa.Column('goals', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('person_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'person_type')
    op.drop_column('users', 'goals')
    op.drop_column('users', 'hobby')
    op.drop_column('users', 'about')
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
